export {SAVE_CITY, REMOVE_CITY, WEATHER_NOW, WEATHER_FORECAST};

const SAVE_CITY = "SAVE_CITY";
const REMOVE_CITY = "REMOVE_CITY";
const WEATHER_NOW = "WEATHER_NOW";
const WEATHER_FORECAST = "WEATHER_FORECAST";
